#!/bin/bash

# Install Unturned Server
steamcmd +force_install_dir /data +login anonymous +app_update 1110390 validate +quit

cp -R /data/Extras/Rocket.Unturned /data/Modules/

cp /StartServer.sh /data

mkdir -p /data/Servers/EndzeitServer/Server
cp /Commands.dat /data/Servers/EndzeitServer/Server

cd /data
./StartServer.sh